services:
  qv-generator:
    build: 
      context: ../
      dockerfile: docker/generator/Dockerfile
    container_name: qv-generator
    environment:
      - IN_DOCKER=1
    volumes:
      - qv-files:/app/output
      - ../config.yaml:/app/config.yaml:ro
    restart: on-failure
    networks:
      - qv
    profiles:
      - default
      - mariadb
      - full
    
  qv-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: qv-web
    volumes:
      - qv-files:/usr/share/nginx/html/plots:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - qv-generator
    networks:
      - qv
    profiles:
      - default
      - mariadb
      - full

  mariadb:
    image: mariadb:11.8
    container_name: qv-test-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rSecret
      - MYSQL_DATABASE=test_data
      - MYSQL_USER=queryviz
      - MYSQL_PASSWORD=S3cretz
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - qv
    profiles:
      - mariadb
      - full
    command: --max-connections=200 --innodb-buffer-pool-size=256M

networks:
  qv:
    external: true

volumes:
  qv-files:
    name: qv-files
