version: '3.8'

services:
  qv-generator:
    build: 
      context: ../
      dockerfile: docker/generator/Dockerfile
    container_name: qv-generator
    environment:
      - IN_DOCKER=1
    volumes:
      - qv-files:/app/output
      - ../config.yaml:/app/config.yaml:ro
    restart: on-failure
    
  qv-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: qv-web
    volumes:
      - qv-files:/usr/share/nginx/html/plots:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - qv-generator

volumes:
  qv-files:
    name: qv-files
