# We have the following profiles:
#   - default         Only services needed for production
#   - mariadb         A MariaDB service for manual tests
#   - test            A container for automated tests, plus
#                     any database container used by the tests
#  - full             All testing and production services


# To test databases, we set their authentication variables
# here and then we pass them to the relevant containers
x-mariadb-env: &mariadb-env
  MYSQL_ROOT_PASSWORD: rSecret
  MYSQL_DATABASE: test_data
  MYSQL_USER: queryviz
  MYSQL_PASSWORD: S3cretz

services:
  qv-generator:
    build: 
      context: ../
      dockerfile: docker/generator/Dockerfile
      target: qv-gen-app
    container_name: qv-generator
    volumes:
      - qv-files:/app/output
      - ../config.yaml:/app/config.yaml:ro
    restart: on-failure
    networks:
      - qv
    profiles:
      - default
      - mariadb
      - full
    
  qv-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: qv-web
    volumes:
      - qv-files:/usr/share/nginx/html/plots:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - qv-generator
    networks:
      - qv
    profiles:
      - default
      - mariadb
      - full

  qv-test:
    build:
      context: ../
      dockerfile: docker/generator/Dockerfile
      target: qv-gen-test
    container_name: qv-test
    environment:
      <<: *mariadb-env
    profiles:
      - test
      - full
    networks:
      - qv

  mariadb:
    image: mariadb:11.8
    container_name: qv-test-mariadb
    environment:
      <<: *mariadb-env
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - qv
    profiles:
      - mariadb
      - test
      - full

networks:
  qv:
    external: true

volumes:
  qv-files:
    name: qv-files
