#!/usr/bin/gnuplot
# Generated by: Query-Viz
# Project URL: https://github.com/Vettabase/query-viz

set terminal png enhanced font "Arial,12" size {{CHART_WIDTH}},{{CHART_HEIGHT}}
set output '{{OUTPUT_FILE}}'

set title '{{TITLE}}'
set xlabel '{{XLABEL}}'
set ylabel '{{YLABEL}}'

{{GRID}}
set key {{KEY_POSITION}}

# Set colors and styles for different query types
{{STYLE_LINES}}

{{PLOT_LINES}}

# Also create a terminal version for viewing
set terminal dumb 120 30
set output
replot
